name: daily_pics
description: A new Flutter application.
version: 2.5.10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^0.7.0
  event_bus: ^1.1.0
  flutter_staggered_grid_view: ^0.2.7
  image_picker: ^0.5.2
  json_annotation: ^2.0.0
  material_design_icons:
    git:
      url: https://github.com/Yaerin/flutter_packages.git
      path: material_design_icons
  package_info: ^0.4.0+2
  palette_generator: ^0.1.1
  photo_view: ^0.2.2
  scoped_model: ^1.0.1
  share: ^0.6.0+1
  shared_preferences: ^0.5.1+2
  url_launcher: ^5.0.2

dev_dependencies:
  build_runner: ^1.3.1
  json_serializable: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - res/
